-- Enable extension (for password hashing if not yet enabled)
create extension if not exists pgcrypto;

--FOR CHANGING THE DB
-- alter table categories
-- alter column created_at type timestamptz using created_at::timestamptz;

-- alter table categories
-- alter column created_at set default now();

-- alter table categories
-- add column updated_at timestamptz default now();

-- --FOR DESCRIBING
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'items';

-- =====================================
-- ROLES
-- =====================================
create table public.roles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  permissions jsonb default '[]'::jsonb
);

-- =====================================
-- USERS
-- =====================================
create table public.users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  name text not null,
  password text,

  role bigint references public.roles(id),

  sss_number text,
  philhealth_number text,
  pagibig_number text,

  hourly_rate numeric,
  daily_rate numeric,

  is_live_seller boolean,
  is_employee boolean,

  email text,
  address text,
  phone_number text
);
-- =====================================
-- SUPPLIERS
-- =====================================
create table public.suppliers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text,
  contact_number text
);

-- =====================================
-- CATEGORIES
-- =====================================
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  description text not null
);

-- =====================================
-- INVENTORIES
-- =====================================
create table public.inventories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  date_arrived timestamptz,
  box_number text,

  supplier_id bigint,
  category_id bigint,

  quantity numeric not null default 0,
  price numeric not null default 0,
  total numeric not null default 0,

  quantity_left numeric not null default 0,
  total_left numeric not null default 0,

  -- FOREIGN KEYS
  constraint inventories_supplier_fkey
    foreign key (supplier_id)
    references public.suppliers(id)
    on delete set null,

  constraint inventories_category_fkey
    foreign key (category_id)
    references public.categories(id)
    on delete set null
);

-- =====================================
-- ITEMS
-- =====================================
create table public.items (
  id bigint generated by default as identity primary key,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  created_by bigint,
  updated_by bigint,

  date_shipped timestamptz,
  date_returned timestamptz,

  prepared_by bigint,
  live_seller bigint,
  category bigint,

  brand text,
  order_id text,
  mined_from text default '',

  shopee_commission double precision default 0,
  selling_price double precision default 0,
  capital double precision default 0,
  order_income double precision default 0,
  discount double precision default 0,
  commission_rate double precision default 0,
  quantity double precision default 0,
  final_price double precision default 0,

  is_returned boolean default false,

  -- =========================
  -- FOREIGN KEYS
  -- =========================

  constraint items_created_by_fkey
    foreign key (created_by)
    references public.users(id)
    on delete set null,

  constraint items_updated_by_fkey
    foreign key (updated_by)
    references public.users(id)
    on delete set null,

  constraint items_prepared_by_fkey
    foreign key (prepared_by)
    references public.users(id)
    on delete set null,

  constraint items_live_seller_fkey
    foreign key (live_seller)
    references public.users(id)
    on delete set null,

  constraint items_category_fkey
    foreign key (category)
    references public.categories(id)
    on delete set null
);


-- =====================================
-- EXPENSES
-- =====================================
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  description text,
  amount double precision
);

-- =====================================
-- PAYROLLS
-- =====================================
create table public.payrolls (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id bigint,
  days_worked double precision,
  overtime_hours double precision,
  total_daily_pay double precision,
  total_overtime_pay double precision,
  daily_rate double precision not null,
  hourly_rate double precision not null,
  total_commission double precision,
  total_bonus double precision,
  total_deduction double precision,
  gross_pay double precision,
  net_pay double precision,
  start_period date,
  end_period date
);

-- =====================================
-- DEFAULT DATA
-- =====================================
insert into public.roles (name) values
('Superadmin'),
('Admin Head'),
('Admin Assistant'),
('Production Staff'),
('Sales Marketing Head'),
('Housekeeping');

-- =====================================
-- SUPERADMIN ACCOUNT
-- =====================================
insert into public.users (
  name,
  password,
  role,
  sss_number,
  philhealth_number,
  pagibig_number,
  hourly_rate,
  daily_rate,
  is_live_seller,
  email,
  address,
  phone_number
)
values (
  'Superadmin',
  crypt('superadmin123', gen_salt('bf')),
  1,
  'N/A',
  'N/A',
  'N/A',
  '0',
  '0',
  'No',
  'superadmin@gmail.com',
  'Dasmarinas Cavite',
  '09789789789'
);