-- Enable extension (for password hashing if not yet enabled)
create extension if not exists pgcrypto;

--FOR CHANGING THE DB
-- alter table categories
-- alter column created_at type timestamptz using created_at::timestamptz;

-- alter table categories
-- alter column created_at set default now();

-- alter table categories
-- add column updated_at timestamptz default now();

-- =====================================
-- ROLES
-- =====================================
create table public.roles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  permissions jsonb default '[]'::jsonb
);

-- =====================================
-- USERS
-- =====================================
create table public.users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  password text,
  role_id bigint,
  auth_id uuid,
  sss_number text,
  philhealth_number text,
  pagibig_number text,
  hourly_rate text,
  daily_rate text,
  is_live_seller text default 'No',
  is_employee text default 'Yes',
  email text,
  address text,
  phone_number text
);

-- =====================================
-- SUPPLIERS
-- =====================================
create table public.suppliers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text,
  contact_number text
);

-- =====================================
-- CATEGORIES
-- =====================================
create table public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  description text not null
);

-- =====================================
-- INVENTORIES
-- =====================================
create table public.inventories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  date_arrived timestamptz,
  box_number text,
  supplier text,
  quantity text,
  price text,
  total text,
  category text,
  quantity_left text not null default '0',
  total_left text not null default '0'
);

-- =====================================
-- ITEMS
-- =====================================
create table public.items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  timestamp timestamptz,
  prepared_by text,
  brand text,
  order_id text,
  shoppee_commission text default '0',
  selling_price text default '0',
  is_returned text default 'No',
  quantity text default '',
  live_seller text,
  capital text default '0',
  order_income text default '0',
  category text,
  mined_from text default '',
  discount text default '0',
  date_shipped timestamptz,
  date_returned timestamptz,
  commission_rate text
);

-- =====================================
-- EXPENSES
-- =====================================
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  description text,
  amount double precision
);

-- =====================================
-- PAYROLLS
-- =====================================
create table public.payrolls (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id bigint,
  days_worked double precision,
  overtime_hours double precision,
  total_daily_pay double precision,
  total_overtime_pay double precision,
  daily_rate double precision not null,
  hourly_rate double precision not null,
  total_commission double precision,
  total_bonus double precision,
  total_deduction double precision,
  gross_pay double precision,
  net_pay double precision,
  start_period date,
  end_period date
);

-- =====================================
-- DEFAULT DATA
-- =====================================
insert into public.roles (name) values
('Superadmin'),
('Admin Head'),
('Admin Assistant'),
('Production Staff'),
('Sales Marketing Head'),
('Housekeeping');

-- =====================================
-- SUPERADMIN ACCOUNT
-- =====================================
insert into public.users (
  name,
  password,
  role_id,
  sss_number,
  philhealth_number,
  pagibig_number,
  hourly_rate,
  daily_rate,
  is_live_seller,
  email,
  address,
  phone_number
)
values (
  'Superadmin',
  crypt('superadmin123', gen_salt('bf')),
  1,
  'N/A',
  'N/A',
  'N/A',
  '0',
  '0',
  'No',
  'superadmin@gmail.com',
  'Dasmarinas Cavite',
  '09789789789'
);